### ISSUE TITLE
The "LinkAssemblies" task failed unexpectedly

### ISSUE THREAD

**Issue by anjum-chauhan** [Sicos1977/MSGReader#139]
**Describe the bug**
We are using MSGReader for converting the .msg files to pdf in our xamarin forms project. While applying "linker properties" to "Sdk Assemblies Only" in xamarin.Android properties, we are getting the below error-
The "LinkAssemblies" task failed unexpectedly.
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Drawing.Drawing2D.DashStyle' (defined in assembly 'MsgReader, Version=3.4.0.0, Culture=neutral, PublicKeyToken=3ba01cf3434959fa') with scope 'System.Drawing.Common, Version=4.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Drawing.Drawing2D.DashStyle

**To Reproduce**
1. Add MSGReader package in xamarin.Android project.
2. Set "Linker Properties" to "Sdk Assemblies Only" in xamarin.Android project.
3. Try building the solution.
4. You'll get the above mentioned error.

**Expected behavior**
Project should allow to build after Linker properties has been applied to  "Sdk Assemblies Only" and MSGReader is included in the reference

**Desktop (please complete the following information):**
 - OS: [Windows 8.1]

**Note**
Project works fine if linker properties are set to "None"

**Comment by tmmstnchauhan** [comment]
![msgreaderbuilderror](https://user-images.githubusercontent.com/46218360/50511630-5e0fde00-0ab4-11e9-8fef-f521804892ba.JPG)

**Comment by JKennedy24** [comment]
I'm also getting this error on Android and iOS

 Any idea how to resolve it?

**Comment by jonpryor** [comment]
We're still trying to figure out *The* Fix.

We think we have a grasp on the problem, and I have *a* (stupid) workaround.

The fundamental problem is that, at present, when you add the `System.Drawing.Common` NuGet package to a Xamarin.Android application project, *nothing of consequence happens*.  This is easily seen by e.g. editing `MainActivity.cs` to contain:

```csharp
using System.Drawing.Drawing2D;
```

The result will be a CS0234 error, because no `System.Drawing.Drawing2D` namespace can be found, because no "real" `System.Drawing.Common.dll` assembly is being referenced by the C# compiler.

The `LinkAssemblies` error is fundamentally the same: `LinkAssemblies` fails because no "real" `System.Drawing.Common.dll` is provided to the linker, so the required referenced members cannot be resolved.

As of this point in time, I don't know what the correct, long-term, broad-scale fix will be, or when it will be available.

Short-term, there's a quick workaround: Provide the `System.Drawing.Common.dll` assembly *explicitly* to the Android App project.

For example, copy `%USERPROFILE%\.nuget\packages\system.drawing.common\4.5.1\lib\netstandard2.0\System.Drawing.Common.dll` into your project directory, then add an Assembly Reference (`@(Reference)`) to the copied assembly to your `App.csproj`:

```xml
<!-- App.csproj -->
<ItemGroup>
  <Reference Include="System.Drawing.Common">
    <HintPath>Path\To\System.Drawing.Common.dll</HintPath>
  </Reference>
</ItemGroup>
```

This *should* allow *a* `System.Drawing.Common.dll` to be found by the compiler (fixing the CS0234 error above), which will *also* fix the XA2006 linker error.

**Comment by anjum-chauhan** [comment]
Hi Jonathan,

I am able to build the solution with the work around that you provided.
Thanks a ton for the help. Hope we get a proper working solution for this
problem soon :)

Thanks & Regards,
Anjum Chauhan

**Comment by anjum-chauhan** [comment]
I am able to build the solution with the work around that you provided.

**Comment by eduarduamaral** [comment]
> We're still trying to figure out _The_ Fix.
> 
> We think we have a grasp on the problem, and I have _a_ (stupid) workaround.
> 
> The fundamental problem is that, at present, when you add the `System.Drawing.Common` NuGet package to a Xamarin.Android application project, _nothing of consequence happens_. This is easily seen by e.g. editing `MainActivity.cs` to contain:
> 
> ```cs
> using System.Drawing.Drawing2D;
> ```
> 
> The result will be a CS0234 error, because no `System.Drawing.Drawing2D` namespace can be found, because no "real" `System.Drawing.Common.dll` assembly is being referenced by the C# compiler.
> 
> The `LinkAssemblies` error is fundamentally the same: `LinkAssemblies` fails because no "real" `System.Drawing.Common.dll` is provided to the linker, so the required referenced members cannot be resolved.
> 
> As of this point in time, I don't know what the correct, long-term, broad-scale fix will be, or when it will be available.
> 
> Short-term, there's a quick workaround: Provide the `System.Drawing.Common.dll` assembly _explicitly_ to the Android App project.
> 
> For example, copy `%USERPROFILE%\.nuget\packages\system.drawing.common\4.5.1\lib\netstandard2.0\System.Drawing.Common.dll` into your project directory, then add an Assembly Reference (`@(Reference)`) to the copied assembly to your `App.csproj`:
> 
> ```
> 
> <ItemGroup>
>   <Reference Include="System.Drawing.Common">
>     <HintPath>Path\To\System.Drawing.Common.dll</HintPath>
>   </Reference>
> </ItemGroup>
> ```
> 
> This _should_ allow _a_ `System.Drawing.Common.dll` to be found by the compiler (fixing the CS0234 error above), which will _also_ fix the XA2006 linker error.

Thank you very much for helping me solve the problem while compiling the iOS app

**Comment by ZaeemZafar** [comment]
@eduarduamaral  I am also having issues integrating MsgReader into the Xamarin iOS app. I am still receiving [compile time errors](https://github.com/Sicos1977/MSGReader/issues/158) after applying the above fixes. 

Can you please attach a sample project(Xamarin iOS) that reads .msg files successfully.

**Comment by Jacko1394** [comment]
I am also having this problem.  I'd love to use this library in my Xamarin app but cannot due to this issue.
