### ISSUE TITLE
Sender is missing for .msg files.

### ISSUE THREAD

**Issue by ZeyuWilliamFan** [Sicos1977/MSGReader#155]
**Describe the bug**
Sender field is missing after converting to HTML file. (No sender's email address)
[sender_missing.zip](https://github.com/Sicos1977/MSGReader/files/3118879/sender_missing.zip)

**Screenshots**
![sender_missing](https://user-images.githubusercontent.com/13264768/56768644-ecebe900-677c-11e9-8d61-cf74627690f3.PNG)
![expected](https://user-images.githubusercontent.com/13264768/56768647-ecebe900-677c-11e9-8b4f-2d7eb439dfa9.PNG)

**Additional context**
I tracked down, and it appears to be caused by the fix for https://github.com/Sicos1977/MSGReader/issues/26 , where the GetHeaders() method call is moved from bottom of the function to top. When I tried to debug it seems like it cannot get the property value for the sender field. i.e nothing returns for method GetMapiProperty().

If I move back the GetHeaders() call and SetEmailSenderAndRepresentingSender() call to the end of the LoadStorage(), the sender field is correctly parsed.

**Comment by ZeyuWilliamFan** [comment]
Also I noticed that there has been some quite big change regarding the RTF Parser.

Originally the RichTextBox is used for parsing RTF files.
Then somehow it got replaced by:  RTF to HTML Converter Class Library based on: Writing Your Own RTF Converter By Jani Giannoudis

Now it got replaced by RtfPipe, which is available on NuGet.

I tested all three RTF Parser, and there seem to be different issues with regarding to latter two (I can provide source files if you want, but I dont think you maintain these RTF thing, right?). I manually revert back to the RichTextBox which is working fine for me as of now. But really I'm just curious what is the reason behind these RTF Parser replacement? Are there any gaps or security concerns popping up? I would like to have a heads up since it is part of our commercial software's component.

Thanks!

Zeyu

**Comment by Sicos1977** [comment]
The reason why I don't use the richtextbox anymore is because that one is not compatible with .NET standard (core) and had some other issues.

I also peeked inside you MSG file and the sender is missing in there. Outlook just replaces the sender with the e-mail address that is opening the msg file. In my case that is my own e-mail address. So the code is working correctly by not showing it.

![image](https://user-images.githubusercontent.com/6692947/56863233-32dec200-69b4-11e9-8073-1296a305a6fd.png)
