### ISSUE TITLE
Issue with RTFPipe

### ISSUE THREAD

**Issue by omisler** [Sicos1977/MSGReader#165]
In some files I get the following message:

"Could not load file or assembly 'RtfPipe, Version=xxx, Culture=neutral, PublicKeyToken=xxx' or one of its dependencies. The system cannot find the file specified."

I'm using nuget version 3.7.3

**Comment by rmr964** [comment]
Hi,

I'm getting the same issue since updating to 3.7.3 from a very old version (2.5.x i think)
It's working on most .MSG files, but has an issue with the attached the file when using the msgReader.ExtractToFolder method

Exception:
Could not load file or assembly 'RtfPipe, Version=1.0.0.0, Culture=neutral, PublicKeyToken=317a45ec926873fc' or one of its dependencies. The system cannot find the file specified.

StackTrace:

   at MsgReader.Outlook.RtfToHtmlConverter.ConvertRtfToHtml(String rtf)
   at MsgReader.Reader.PreProcessMsgFile(Message message, Boolean hyperlinks, String outputFolder, String& fileName, Boolean& htmlBody, String& body, String& contactPhotoFileName, List`1& attachments, List`1& files)
   at MsgReader.Reader.WriteMsgEmail(Message message, String outputFolder, Boolean hyperlinks)
   at MsgReader.Reader.ExtractToFolder(String inputFile, String outputFolder, Boolean hyperlinks, Nullable`1 messageType, Stream logStream)
   at cManager.frmCaseHistory.PreviewFile(String pFileName) in E:\Source\cManager\cManager\frmCaseHistory.vb:line 406

[Daily report mailbox support@derbydatabases_com folder Spam.zip](https://github.com/Sicos1977/MSGReader/files/3448672/Daily.report.mailbox.support%40derbydatabases_com.folder.Spam.zip)

**Comment by Sicos1977** [comment]
What version number has the RtfPipe dll?

**Comment by rmr964** [comment]
Hi, I can't find the rtfpipe.dll anywhere on my project folder I installed msgReader 3.7.3 via NUGET update in Visual Studio. Where would i find rtfpipe.dll? Do i have to install rtfpipe separately?

**Comment by omisler** [comment]
From what I've seen, the nuget package in the past installed certain version of Rtfpipe.
However, in future releases it was not required and I don't have any version of rtfpipe.dll in my solution.

I noticed that this message only appear for those messages that are on rich text format, and not for those based on html or plain text (hence the rtfpipe error, I conclude).

**Comment by rmr964** [comment]
I've installed RptPipe-Signed v0.7.0.3 and RTFPipe v1.0.7092.25824 and still get the same results

There doesn't seem to a v1.0.0.0 to install. It goes from v0.7.0.6 to 1.0.0.22

**Comment by rmr964** [comment]
solved/hacked it by downloading the solution from github and including the RTFPipe.dll in the MSGReader-master\Assemblies\net45 folder into my solution. Not sure if that's the right thing to do ....

**Comment by Sicos1977** [comment]
Due to the holidays its very crowded at my work and I didn't had the time to fix this issue. I'll try to fix it this weekend.

**Comment by Sicos1977** [comment]
Next release will have the rtfpipe assembly included again

**Comment by Sicos1977** [comment]
I just released version 3.7.4

**Comment by omisler** [comment]
In the new version this bug has happened again.
