### ISSUE TITLE
Rtf body extracted with invalid characters

### ISSUE THREAD

**Issue by Zoidster** [Sicos1977/MSGReader#198]
**Describe the bug**
I tried converting a msg mail with a rtf body to a standalone rtf file by writing the BodyRtf content to a new file.
The new file produces an error when opened with word and contains broken characters.
Could this be an encoding error or due to the images in the mail?

[Zip with msg file and extracted rtf file](https://github.com/Sicos1977/MSGReader/files/4085590/Downloads.zip)

**To Reproduce**
Use the attached file and read the BodyRtf property.

**Expected behavior**
When opening the mail in outlook normal text content is visible. So I guess that is the expected outcome.

**Desktop**
 - OS: Win10
 - Version 3.7.14
 - Framework: netstandard2.0

**Comment by Sicos1977** [comment]
At the moment I am on a skiing holiday I'll try to look into it next week




Met vriendelijke groet,


Kees van Spelde







On Mon, Jan 20, 2020 at 11:34 AM +0100, "Luca" <notifications@github.com> wrote:












Describe the bug

I tried converting a msg mail with a rtf body to a standalone rtf file by writing the BodyRtf content to a new file.

The new file produces an error when opened with word and contains broken characters.

Could this be an encoding error or due to the images in the mail?


Zip with msg file and extracted rtf file


To Reproduce

Use the attached file and read the BodyRtf property.


Expected behavior

When opening the mail in outlook normal text content is visible. So I guess that is the expected outcome.


Desktop

OS: Win10
Version 3.7.14
Framework: netstandard2.0

**Comment by Sicos1977** [comment]
I see that you used a very complex RTF body, MSGReader supports RTF but not as complex as this. Is this a situation that you are facing in real life or just a test scenario that you have made to see what the limits of MSGReader are?

**Comment by Sicos1977** [comment]
I pulled the RTF directly from the MSG file and this also seems to be corrupt. There is nothing that I can do about something that is already bad to start with.


[rtfbody.zip](https://github.com/Sicos1977/MSGReader/files/4161233/rtfbody.zip)

**Comment by Zoidster** [comment]
Oh I didn't know that, the file was just one of the test cases I threw at my project.
Sorry for wasting your time
