### ISSUE TITLE
The specified media type is invalid..

### ISSUE THREAD

**Issue by JiriOgurek** [Sicos1977/MSGReader#206]
When I call Message.Load() I get this exception: "The specified media type is invalid.."

BTW, it's raised in set_MediaType setter method.

See attached sample, please:
[testEmail.zip](https://github.com/Sicos1977/MSGReader/files/4298408/testEmail.zip)

Running on Windows 10, .NET Core v3.1 release.

Thank you for your kind help :-)

**Comment by ssmelov** [comment]
Hello Jiri, I guess that could be because of the content-type in the header of your email: "Content-Type: text/html; 7Bit". 
All the values except for the media-type have to have names(keys) (for example: charset, name etc), otherwise MsgReader is not able to handle it.

**Comment by ssmelov** [comment]
Hello,

I prepared a pull-request to process parts of "Content-Type" header with empty key only once.
@Sicos1977, would you have a look please?

I also got this issue a couple of days ago. Here are the details.
If email contains content-type header where more than one field doesn't have a key/name, then the parsing of content-type is failed.

Here is an example:

`Content-Type: text/html; Windows-1252`

This will fail, since a content-type parser will try to parse 'Windows-1252' as a media type and will fail since it doesn't have an expected format 'type/subtype'.

Here is an example of a such email (which opens in Outlook, but can't be loaded by MsgReader because of the content-type parser):
[email-with-content-type-with-charset-key-missing.zip](https://github.com/Sicos1977/MSGReader/files/4298660/email-with-content-type-with-charset-key-missing.zip)
