### ISSUE TITLE
MsgReader library misses to add <br> tags at the end of some sentences

### ISSUE THREAD

**Issue by SDSHugh07** [Sicos1977/MSGReader#210]
**Describe the bug**
The MsgReader library misses to add <br> tags at the end of these sentences in file ‘RE 2月チャージについて.msg’:
一郎さん
児玉です。おつかれさまです。
連絡ありがとう！でも今月は引き取り先が見つかりました。
また適宜相談します。

**To Reproduce**
I have tested ‘RE 2月チャージについて.msg’ with and without <br> tag (use to break the current line and move to next line).
When I add <br> tag to the input from MsgReader library segmentation remains intact.

Input from MsgReader(binary data)
ä¸€éƒŽã•ã‚“
å…çŽ‰ã§ã™ã€‚ãŠã¤ã‹ã‚Œã•ã¾ã§ã™ã€‚
é€£çµ¡ã‚ã‚ŠãŒã¨ã†ï¼ã§ã‚‚ä»Šæœˆã¯å¼•ãå–ã‚Šå…ˆãŒè¦‹ã¤ã‹ã‚Šã¾ã—ãŸã€‚
ã¾ãŸé©å®œç›¸è«‡ã—ã¾ã™ã€‚

After adding <br> tags
ä¸€éƒŽã•ã‚“<br>
å…çŽ‰ã§ã™ã€‚ãŠã¤ã‹ã‚Œã•ã¾ã§ã™ã€‚<br>
é€£çµ¡ã‚ã‚ŠãŒã¨ã†ï¼ã§ã‚‚ä»Šæœˆã¯å¼•ãå–ã‚Šå…ˆãŒè¦‹ã¤ã‹ã‚Šã¾ã—ãŸã€‚<br>
ã¾ãŸé©å®œç›¸è«‡ã—ã¾ã™ã€‚<br>

**Expected behavior**
<br> tag should be added at line endings

**Additional context**
I will send the problem files directly to you via email

**Comment by Sicos1977** [comment]
Hi,




Sorry for the late response but at the moment I'm very busy with work due to the corona crisis. 




Met vriendelijke groet,


Kees van Spelde







On Tue, Mar 17, 2020 at 3:32 AM +0100, "SDSHugh07" <notifications@github.com> wrote:















Describe the bug

The MsgReader library misses to add 
 tags at the end of these sentences in file ‘RE 2月チャージについて.msg’:

一郎さん

児玉です。おつかれさまです。

連絡ありがとう！でも今月は引き取り先が見つかりました。

また適宜相談します。


To Reproduce

I have tested ‘RE 2月チャージについて.msg’ with and without 
 tag (use to break the current line and move to next line).

When I add 
 tag to the input from MsgReader library segmentation remains intact.


Input from MsgReader(binary data)

ä¸€éƒŽã�•ã‚“

å…�çŽ‰ã�§ã�™ã€‚ã�Šã�¤ã�‹ã‚Œã�•ã�¾ã�§ã�™ã€‚

é€£çµ¡ã�‚ã‚Šã�Œã�¨ã�†ï¼�ã�§ã‚‚ä»Šæœˆã�¯å¼•ã��å�–ã‚Šå…ˆã�Œè¦‹ã�¤ã�‹ã‚Šã�¾ã�—ã�Ÿã€‚

ã�¾ã�Ÿé�©å®œç›¸è«‡ã�—ã�¾ã�™ã€‚


After adding 
 tags

ä¸€éƒŽã�•ã‚“


å…�çŽ‰ã�§ã�™ã€‚ã�Šã�¤ã�‹ã‚Œã�•ã�¾ã�§ã�™ã€‚


é€£çµ¡ã�‚ã‚Šã�Œã�¨ã�†ï¼�ã�§ã‚‚ä»Šæœˆã�¯å¼•ã��å�–ã‚Šå…ˆã�Œè¦‹ã�¤ã�‹ã‚Šã�¾ã�—ã�Ÿã€‚


ã�¾ã�Ÿé�©å®œç›¸è«‡ã�—ã�¾ã�™ã€‚



Expected behavior


 tag should be added at line endings


Additional context

I will send the problem files directly to you via email

**Comment by Sicos1977** [comment]
Looking into it now

**Comment by Sicos1977** [comment]
This commit will add the br tags

983103ed3feec6887fa74e4418952721ed9ecda1

**Comment by SDSHugh07** [comment]
Thank you very much , Sicos1977!

**Comment by SonalRana** [comment]
Hi Kees,
 
Is there any specific reason why **</br>** was added at the end of sentence instead of <br/>?

With the testing line break fix, I figured that the new tag added  is </br> but the it should be <br/>. So, even though tags are added it doesn’t have any impact on the output.
<br> beginning of a tag
</br>  ending of a tag
<br/>  self closing tag 
.I think <br> tag should be paired with </br>. Or adding <br/> should do the job.

Please do let me know what you think about this.

**Comment by Sicos1977** [comment]
Where did you detect this? Is br added from code or is it inside the html body?

**Comment by SonalRana** [comment]
It is inside html body. Will share the output via email.
