### ISSUE TITLE
HTML links have empty content

### ISSUE THREAD

**Issue by aimotrens** [Sicos1977/MSGReader#225]
Hi, I have found a problem in Version 3.7.28.
The HTML links have no content.
I have tested this with mails from Outlook.

In version 3.7.26 I get this:
```html
		<p class=MsoNormal><a href="https://www.google.de/">https://www.google.de/</a>
			<o:p></o:p>
		</p>
```

Since 3.7.28 I get this:
```html
		<p class=MsoNormal><a href="https://www.google.de/"></a>
			<o:p></o:p>
		</p>
```

**Comment by Sicos1977** [comment]
Can you send me the file that is giving this problem? Please zip the msg file before sending it to sicos2002@hotmail.com

**Comment by aimotrens** [comment]
Mail has been sent

**Comment by jokokko** [comment]
Noticed the same problem upon upgrade. Think it's introduced in `c292cdffc0cbce843233bb2c0b73ebe31a7cc685` (processing of RTF fields). More specifically, how `Fldinst`, `Fldrslt` and contained `htmlrtf` are processed or propagate in the stack on processing of RTF body.

**Comment by Sicos1977** [comment]
> Noticed the same problem upon upgrade. Think it's introduced in `c292cdffc0cbce843233bb2c0b73ebe31a7cc685` (processing of RTF fields). More specifically, how `Fldinst`, `Fldrslt` and contained `htmlrtf` are processed or propagate in the stack on processing of RTF body.

You are correct, it had to do with that commit. That was a fix for another problem. I rolled back that fix and tried the mail that had an error and that one still seems to be fixed. So I removed the field parsing, it is probably fixed with another fix I also did.

Please download this package to make the hyperlinks work again --> https://www.nuget.org/packages/MSGReader/3.7.29

Package version 3.7.28 is from now on deprecated.
