### ISSUE TITLE
Attachement content is embedded in Email body

### ISSUE THREAD

**Issue by FrKaram** [Sicos1977/MSGReader#254]
I use MsgReader to extract data from EML files (those EML are extracted from a mailbox using openPOP.NET).
The email are originally generated by a library (not on my part) for which I try to get a name / version.

Those EML open "correctly" in MS Outlook ie I see the HTML body and PDF attachements separated.

But when I open those same files with MsgReader, it consider the body and attachements as being the same thing so attachement.count = 0 and body total size include the attachements size. 
MsgReader should be able to separate body from attachements as Outlook does.

I've started debugging MsgReader and it seems to me that the problem comes from the fact that the EML contains multiple "multiparts" of different types :
- multipart/mixed
- multipart/alternative
- multipart/related

I use MsgReader 3.10.0.

I've asked the owner of the emails if I can share a sample with you. I'm waiting for his answer.

**Comment by Sicos1977** [comment]
MSGReader is made to handle msg files and optional EML files. If you only want to handle EML files that it is better to use MailKit in combination with MimeKit... even Microsoft shows examples for these 2 libraries on their site

https://github.com/jstedfast/MailKit
https://github.com/jstedfast/MimeKit

MailKit can be used instead of OpenPop.Net ... MailKit is faster and handles all the weird things with Google mails much better.

**Comment by FrKaram** [comment]
Thanks for the advice.
