### ISSUE TITLE
Why so many updates?

### ISSUE THREAD

**Issue by TonyValenti** [Sicos1977/MSGReader#346]
Also, why did you delete all the old packages from Nuget.org?

**Comment by Sicos1977** [comment]
Hi,

_Why so many updates_ ... because I did a lot of fixes lately and added new features.

- TNEF support is added
- I once and for all fixed horrible problems when decoding encoded chars from RTF when an e-mail contained mixed languages like Chinese, Korean and US english. It took me forever to figure out (due to lack of good documentation from Microsoft) how to decode all of these without any problems (so there were quite a few updates for that)
- Other fixes and cleanups.

And no the old packages are still on Nuget you just don't see them in the listing because I hid them because I was tired of finding out that people were reporting bugs in older version that were already fixed in newer versions.
