### ISSUE TITLE
Return of a strong name

### ISSUE THREAD

**Issue by patrik-pis** [Sicos1977/MSGReader#373]
It would be possible to bring back a strong name. We have several projects that are strong name type and we also need to install assembly into GAC. Without strong name we can't update from version 3.9.0. Removing strong name from projects is not possible on our side.

**Comment by Sicos1977** [comment]
Sorry but that is almost impossible todo. I always used strong named assemblies but since Microsoft made this more or less obsolete there are more and more nuget packages that don't implement this anymore. Because of this is is very hard to find strong named packages to use in MSGReader. That is also one of the main reasons I also dropped support for this.

**Comment by Sicos1977** [comment]
You could try this to see if you still get the non signed assemblies loaded --> https://learn.microsoft.com/en-us/dotnet/standard/assembly/disable-strong-name-bypass-feature
