### ISSUE TITLE
MAPI Property has an unsupported (COM object that has been separated from its underlying RCW cannot be used.)

### ISSUE THREAD

**Issue by perumalsamya** [Sicos1977/MSGReader#90]
Hi, 
I am facing run time error in some random cases.  I created new contact and I tried to extract the information. but I get the run time error when I try to access contact object.

   using (var msg = new MsgReader.Outlook.Storage.Message("test.msg"))
            {
                var contact = msg.Contact;
            }
Please watch the below video to know the error if needed
https://www.screencast.com/t/37aufewZ7qQ5
Thanks
Perumal

**Comment by Sicos1977** [comment]
Sorry for the very late response. I missed your issue. As the error says the contact property is an unsupported type. Can you send me the MSG file so that I can peek around in it to see if it is possible to add support for that property type.

You can send the MSG file to sicos2002@hotmail.com

Greetings,
Kees van Spelde

**Comment by Sicos1977** [comment]
Did you send me the msg file?

**Comment by Sicos1977** [comment]
I'm closing this issue because I removed all the iStorage references from code. A new version (that is not yet released on NuGet) doesn't use this anymore. So there are also no COM objects anymore. See commit 2d4fd5d879e8b8dbb9b7492fa09c34177af2611c for more information.
